### ISSUE TITLE
about how to learn lua

### ISSUE THREAD

**Issue by AidenLeee** [0kk470/pil4#10]
### 你好！
很抱歉以这种方式来尝试联系你，不过我最近真的很 struggle ，先自我介绍一下，我是一名刚毕业的学生，之前在校时学的都是 Java，在找实习的时候也是奔着 Java 去的，但是阴差阳错的是我最后进了一间还算大的游戏公司，在那时我第一次接触到了游戏开发，但是那间公司用的是自研的引擎，并且公司文化很狼性，所以我没有选择留下，迷茫了一段时间后，我觉得选择 Unity 开发这一条路走下去。在学了几个月的 C# 与 Unity 之后，我又做了个项目来求职，但是当我打开招聘软件后，我发现很多公司都要求会 lua ，所以我又马上学了起来，但是对于这门语言，我是真的不知道如何学习，以及学到什么程度能通过面试，我目前就是通过阅读 《Lua程序设计》 这一本书来学习的，可是进度真的好慢，语法格式这些的还好，但是对于各种标准库，我觉得不知道如何下手。在寻找这本书的习题答案参考时发现了你的 github ，不知道您是否可以在学习这门语言以及在职业生涯或者找工作面试复习方面给予一点建议！

**Comment by 0kk470** [comment]
### 你好！

一般公司对应届生的要求还是基础扎实。

就对Lua的掌握程度来说，我个人觉得基础要求就是：
* 掌握基础语法。
* 熟练使用table，了解其实现原理，理解元表的机制，理解pairs等迭代器的机制。
* 理解协程的机制。
* 理解函数闭包的机制。
* 了解lua的gc算法。

总的来说，你只要把《Lua程序设计》前21章吃透了就行。
更功利点的话，重点学习chapter4、5、6、9、10、12、17、18、20、21。
我看你也在学习Unity，那么可以去了解下[xlua](https://github.com/Tencent/xLua)，这样也可以尝试下使用Lua+Unity来做项目学习。

另外有关面试，我的建议就是：
* 一边学习一边去面试，根据面试结果查漏补缺，不要害怕失败，每次面试后总结写下博客之类的记录下知识点，多试几次后自然就会得心应手了。
* 也可以去牛客网、知乎什么的搜搜相关的面经。
* 最重要的还是打好你的专业基础(数据结构与算法、操作系统、计组这些)。


职业生涯这个因人而异，我没法给太多建议，重要的还是以你自己的目标为驱动，问清楚自己到底想要什么，然后拆分成不同阶段的目标努力去实现即可。学习路线可以参考 [游戏程序员的学习之路](https://github.com/miloyip/game-programmer)。

**Comment by AidenLeee** [comment]
### 感谢！
在昨天看到你的建议后，我现在才开始写下这个评论，并不是不重视，相反地，我觉得如果对你的建议不加思索地感谢与回复是一种敷衍。然后我思考了很多，也去了解了很多，这让我对这个职业有了很多新的认识，这个认识不是指某个语言，某项技术，而是更系统性的整体方面，有种自上而下的感觉，确实对我目前所处的思想状态有所帮助。

同时，我深知基础的重要性，这也是我获取知识的一个偏好，我不喜欢中文网络上的一些浮躁与急功近利的行为。仅在网络上确实难以了解一个人，每个人当下所处的阶段也不同，所以你给的建议已经非常实际有用，再次感谢！希望以后还能有机会和你继续探讨技术问题。

**Comment by 0kk470** [comment]
客气了，祝工作顺利，事业有成。
