### ISSUE TITLE
ch05.ex5.8

### ISSUE THREAD

**Issue by AidenLeee** [0kk470/pil4#11]
### 问题描述
`table.my_fastConcat` 函数中使用了 `string.byte()` 但是没有限定范围，所以只会返回第一个 character 的 ASCII 码。
个人修改为:
```lua
    for i = 1,#t do
        -- temp = { string.byte(tostring(t[i])) }
        str = tostring(t[i])
        temp = { string.byte(str, 1, #str) } 
        for j = 1,#temp do
          result[#result + 1] = temp[j]
       end
    end
```
- 但是，由于这样会使 result 中添加太多的元素，传入的表较大的话很容易抛出异常：
```shell
lua5.3: ex5.8.lua:42: too many results to unpack
stack traceback:
        [C]: in function 'table.unpack'
        ex5.8.lua:42: in function 'table.my_fastConcat'
        ex5.8.lua:59: in local 'test5_8'
        ex5.8.lua:62: in main chunk
        [C]: in ?
```
- 当然，如果`table.my_fastConcat` 函数的初衷只是顺带一提拿来表达快慢之分，默认输入的字符串都只有一个字符，那么这个 issue 没有意义。

**Comment by 0kk470** [comment]
* `string.byte`这个确实遗漏了范围指定，你的修改是正确的。

* `table.unpack`异常的问题是`result`的长度（`table.unpack`的返回值数量）超过了函数调用栈的最大容量导致的。
![image](https://github.com/0kk470/pil4/assets/25216715/c3ecc356-3eb2-45ec-a6dd-fe1f9d784f62)
![image](https://github.com/0kk470/pil4/assets/25216715/0809f634-c390-4a40-b987-0d7a84fcfd3c)
其实就是栈溢出了，算是一种极端情况的非正常调用，在正式开发环境中注意下就好。
