### ISSUE TITLE
Exercise 17.3

### ISSUE THREAD

**Issue by fanhestyle** [0kk470/pil4#7]
Exercise 17.3: What happens in the search for a library if the path has some fixed component (that is, a
component without a question mark)? Can this behavior be useful?

Add a fixed file name to lua path is a really bad decision, because every require statement with a non-exist module will load this file

example lua code:

-- /mnt/dep/lua/hello/sayhi.lua
local sayhi = {}
function sayhi.show()
 print('hi!!!!!!!!!!')
end
return sayhi

--test.lua
package.path = package.path .. ';/mnt/dep/lua/hello/sayhi.lua'
local s = require "go1111"  --go1111 is a non-exist module name
s.show()

如果在lua的搜索path中添加一项绝对路径的文件名，会导致require一个不存在的模块时，这个模块都会搜索到固定文件名的文件作为它导入的模块

**Comment by 0kk470** [comment]
> Exercise 17.3: What happens in the search for a library if the path has some fixed component (that is, a component without a question mark)? Can this behavior be useful?
> 
> Add a fixed file name to lua path is a really bad decision, because every require statement with a non-exist module will load this file
> 
> example lua code:
> 
> -- /mnt/dep/lua/hello/sayhi.lua local sayhi = {} function sayhi.show() print('hi!!!!!!!!!!') end return sayhi
> 
> --test.lua package.path = package.path .. ';/mnt/dep/lua/hello/sayhi.lua' local s = require "go1111" --go1111 is a non-exist module name s.show()
> 
> 如果在lua的搜索path中添加一项绝对路径的文件名，会导致require一个不存在的模块时，这个模块都会搜索到固定文件名的文件作为它导入的模块

感谢反馈，已修正为[新的答案](https://github.com/0kk470/pil4/blob/master/chapter17/chapter17.lua)

另外我又测了下，每次加载不存在的模块时，如果模块名不一样，哪怕固定路径相同也会分配新的内存来缓存module。
