### ISSUE TITLE
chapter13，13.6解答有误

### ISSUE THREAD

**Issue by AiFuYou** [0kk470/pil4#8]
--- 练习13.6 用lua实现一个bit数组。它应该支持下列操作
--- ● newBitArray(n) (创建一个有n个bit的数组)
--- ● setBit(a ,n ,v) (将boolean值 v 赋值给数组a的n位bit)
--- ● testBit(a ,n) (返回一个n位bit的boolean值v)
local function newBitArray(n)
   local array = {}
   for i = 1,n do array[i] = false end
   return array
end

local function setBit(a,n,v) 
   if a and a[n] then a[n] = v end--这里判断永远为假，无法赋值，因为a[n]的值只能为false或nil
end

local function testBit(a,n) 
  return a and a[n]
end

local ta = newBitArray(10)
setBit(ta, 1, true)
teseBit(ta, 1)--false

**Comment by 0kk470** [comment]
> --- 练习13.6 用lua实现一个bit数组。它应该支持下列操作 --- ● newBitArray(n) (创建一个有n个bit的数组) --- ● setBit(a ,n ,v) (将boolean值 v 赋值给数组a的n位bit) --- ● testBit(a ,n) (返回一个n位bit的boolean值v) local function newBitArray(n) local array = {} for i = 1,n do array[i] = false end return array end
> 
> local function setBit(a,n,v) if a and a[n] then a[n] = v end--这里判断永远为假，无法赋值，因为a[n]的值只能为false或nil end
> 
> local function testBit(a,n) return a and a[n] end
> 
> local ta = newBitArray(10) setBit(ta, 1, true) teseBit(ta, 1)--false

感谢反馈，很抱歉提供了错误的答案，已经修改，并且加了一些[错误检查](https://github.com/0kk470/pil4/blob/master/chapter13/chapter13.lua)。
