### ISSUE TITLE
Chapter5 Exercises 5.6 

### ISSUE THREAD

**Issue by fanhestyle** [0kk470/pil4#9]
按照Lua官方给出的文档：一个表中的非自然数的索引不影响该表是否被判定为一个合法的序列
Reference：“Note that non-natural keys do not interfere with whether a table is a sequence”
    3.4.7 – The Length Operator
    https://www.lua.org/manual/5.3/manual.html#3.4.7

解答中给出的代码在如下的测试用例中无法通过：
print(isValidSequence({1,a=2,3,4}))  --> 输出 false，按照Lua文档应该的输出true

以下是我编写的函数，仅供参考

```
local function isValidSequence(a)
    if type(a) ~= "table" then return false end

    local numKeys = 0
    for _ in ipairs(a) do numKeys = numKeys + 1 end

    for k in pairs(a) do
        if math.type(k) == "integer" and math.tointeger(k) > numKeys then
            return false
        end
    end
    
    return true
end
```

**Comment by 0kk470** [comment]
之前的解答准确来说是判断一个table是不是纯数组。

主要是因为当初看原文是看到这句描述
![7CR$YT4 {X}U 34CECGG}9C](https://user-images.githubusercontent.com/25216715/153831077-9de1edda-e532-4a61-8b01-b02882ffc35d.png)
然后以这个定义作为前提进行的解答。

如果以manual里提到的定义为基准
```
In words, a border is any (natural) index in a table where a non-nil value is followed by a nil value (or zero, when index 1 is nil).

A table with exactly one border is called a sequence.
```
那么确实你的solution更合题意。

这里我还是以你的为准吧，感谢反馈。

Edited: `math.type(k) == "integer"`判断通过后，我觉得可以直接比较，不需要再用math.tointeger转换了。
